version: "3"

volumes:
  local_postgres_data: {}

services:
  thjonustukerfi-webapi:
    build: ./Bakendi/ThjonustukerfiWebAPI
    image: thjonustukerfi-webapi:latest
    container_name: thjonustukerfi-webapi
    ports:
      - "5000:6000"
      - "5001:6001"
    depends_on: 
      - "postgres_tjonustukerfi_image"
    networks:
      - "thjonustukerfi-network"
    environment:
      ASPNETCORE_URLS: https://+:6001;http://+:6000;
      DB_CONNECTION_STRING: Host=postgres_tjonustukerfi_image;Port=5432;Database=${postgresDatabase};Username=${postgresUser};Password=${postgresPassword}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
  
  postgres_tjonustukerfi_image:
    image: postgres:latest
    container_name: postgres_tjonustukerfi_image
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${postgresUser}
      POSTGRES_PASSWORD: ${postgresPassword}
      POSTGRES_DB: ${postgresDatabase}
    networks:
      - "thjonustukerfi-network"
    
  thjonustukerfi-react-app:
    build:
      context: ./Vefur/thjonustukerfi-react-app
      args: 
        - API_URL=http://192.168.1.230
        - API_PORT=5000
    image: thjonustukerfi-react-app:latest
    container_name: thjonustukerfi-react-app
    ports:
      - "80:3000"
    networks:
      - "thjonustukerfi-network"

volumes:
  db_volume:

networks:
  thjonustukerfi-network:
    driver: bridge
