version: "3"

volumes:
  local_postgres_data: {}

services:
  thjonustukerfi-webapi:
    build: ./Bakendi/ThjonustukerfiWebAPI
    image: thjonustukerfi-webapi:latest
    container_name: thjonustukerfi-webapi
    ports:
      - "6000:6000"
      - "5001:6001"
    depends_on: 
      - "postgres_image"
    networks:
      - "thjonustukerfi-network"
    environment:
      ASPNETCORE_URLS: https://+:6001;http://+:6000;
      DB_CONNECTION_STRING: Host=postgres_image;Port=5432;Database=${postgresDatabase};Username=${postgresUser};Password=${postgresPassword}
  
  postgres_image:
    image: postgres:latest
    container_name: postgres_image
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${postgresUser}
      POSTGRES_PASSWORD: ${postgresPassword}
      POSTGRES_DB: ${postgresDatabase}
    networks:
      - "thjonustukerfi-network"
    
  thjonustukerfi-react-app:
    build: ./Vefur/thjonustukerfi-react-app
    image: thjonustukerfi-react-app:latest
    container_name: thjonustukerfi-react-app
    ports:
      - "80:3000"
    networks:
      - "thjonustukerfi-network"
    environment: 
      REACT_APP_API_ENDPOINT: http://192.168.111.230
      REACT_APP_API_PORT: 5000

volumes:
  db_volume:

networks:
  thjonustukerfi-network:
    driver: bridge
